<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 2019/11/13
 * Time: 19:16
 */

namespace app\index\controller;


use think\Controller;
use think\Db;

class Reduce extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }

    public function save()
    {
        $uid = $this->request->id;
        $data = $this->request->post();
        $gid = $data['gid'];
        $sale = $data['price'];
        $model = model('Reduce');
        $cart = $model->queryone($uid);
        $cid = $cart['cid'];
        if ($cart) {
            $IncRes='';
            $insertRes='';
            $extramodel = model('Reducemidel');
            $goodsInfo = $extramodel->queryone(['uid' => $uid, 'gid' => $gid]);
            if ($goodsInfo) {
                $IncRes = $extramodel->goodsnumInc(['uid' => $uid, 'gid' => $gid]);
            } else {
                $insertRes = $extramodel->insertgoods(['cid' => $cid, 'gid' => $gid, 'num' => 1, 'status' => 1, 'uid' => $uid]);
            }
            $numberInc = $model->cartInc($uid, 'total');
            $priceInc = $model->cartInc($uid, 'price', $sale);
            if (($IncRes && $numberInc && $priceInc) || ($insertRes && $numberInc && $priceInc)) {
                Db::commit();
                return json([
                    'code'=>config('code.success'),
                    'msg'=>'购物车删除成功',
                ]);
            } else {
                Db::rollback();
            }
        } else {
            Db::startTrans();
            $arr = ['id' => $uid, 'total' => 1, 'price' => $data['price']];
            $rows = $model->insertCart($arr);
            $cid = $model->getLastInsId();
            $goods = ['cid' => $cid, 'gid' => $data['gid'],
                'num' => 1, 'status' => 1, 'uid' => $uid
            ];
            $result = Db::table('cart_extra')->insert($goods);
            if ($rows && $result) {
                Db::commit();
                return json([
                    'code' => config('code.success'),
                    'msg' => "删除成功",
                    'data'=>[
                        'cid'=>$cid,'uid'=>$uid
                    ]
                ]);
            } else {
                Db::rollback();
            }
        }
    }

}